# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FIT3178-Lab04' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIT3178-Lab04
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

end
